version:  "3.9"
services:
  api: 
    container_name: api-task 
    build: .
    volumes: 
      - .:/usr/src/app
    ports: 
      - "3000:3000"
    links:
      - db
  db:
    container_name: db_task
    image: mongo
    volumes: 
      - ./db:/data/db
    ports: 
      - "4000:4000"